---
title: "CS01: Biomarkers of Recent Use"
author: "Derek, Eddie, Rainer"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Introduction

```{r setup, include=FALSE}
# control global Rmd chunk settings
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


### Load packages

```{r load-packages, message=FALSE}
library(tidymodels)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

## Question
What's the best policy for determining impairment - which fluid, which chemical and at what cutoff?

## The Data


### Data Import

```{r}
Blood = read.csv("data/Blood.csv")
Breath = read_csv("data/Breath.csv")
OF = read.csv("data/OF.csv")

```

### Data Wrangling

```{r}

```

## Analysis

```{r}

Blood = Blood |>
  filter(Treatment == "Placebo")

compound_scatterplot_group <- function(dataset, compound, timepoints){
  if(max(dataset[,compound],na.rm=TRUE)==0){
    print(
      dataset |> 
        filter(!is.na(time_from_start)) |>
        ggplot(aes_string(x="time_from_start", 
                          y=compound,
                          color="group")) + 
        geom_point() +
        geom_vline(data=timepoints, aes(xintercept=as.numeric(stop)), 
                   linetype="dashed", 
                   color="gray28") +
        scale_color_manual(values=c("#19831C", "#A27FC9")) +
        scale_y_continuous(limits=c(0,3)) +
        theme_classic() +
        theme(legend.position="bottom",
              legend.title=element_blank()) +
        labs(x='Time From Start (min)',
             y=gsub('GLUC', 'gluc',gsub("_", "-", toupper(compound))))
    )}else{
      print(
        dataset |> 
          filter(!is.na(time_from_start)) |>
          ggplot(aes_string(x="time_from_start", 
                            y=compound,
                            color="group")) + 
          geom_point() +
          geom_vline(data=timepoints, aes(xintercept=as.numeric(stop)), 
                     linetype="dashed", 
                     color="gray28")  +
          scale_color_manual(values=c("#19831C", "#A27FC9")) +
          theme_classic() +
          theme(legend.position="bottom",
                legend.title=element_blank()) +
          labs(x='Time From Start (min)',
               y=gsub('GLUC', 'gluc', gsub("_", "-", toupper(compound))))
      )
    }
}


scatter_wb <- map(compounds_WB, ~ compound_scatterplot_group( 
    dataset=Blood, 
    compound=.x, 
    timepoints=Timepoint))


```

### Exploratory Data Analysis

```{r}


```

### Data Analysis

```{r}

```

### Results


### Discussion


## Conclusion
